### ISSUE TITLE
TimeStretxchPlayer Request

### ISSUE THREAD

**Issue by circuitikzuser** [jwagner/playitslowly#23]
I cannot find the forum for TimeStretchPlayer by the same author.

I am just wondering if it would be able to add saveable bookmarks so that I can save the markers used for looping sections within a loaded clip for future use.

It would really be a great addition.

At the moment it just remembers a marker for looping when you load the file, but you cannot save a bookmark file for different loops within the same clip used.

**Comment by jwagner** [comment]
Hi circuitikzuser,

I like the idea of having a way to save multiple markers (and possibly also track progress) per song.
Because it's web based it's not quite easy to get a nice ux for this (I can't read arbitrary files).
For now I'll keep track of the feature request, if I find some time I'll try to come up with a nice solution.
I'll let you know once it's addressed.

Cheers,
Jonas

**Comment by circuitikzuser** [comment]
Thank you very much.
